name: flutter_aop
description: "Annotation driven proxies to add lightweight AOP style hooks to Flutter code."
version: 0.0.1+2
homepage: https://github.com/KoreanTuna

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  source_gen: ^4.1.0
  analyzer: ^8.1.1
  build: ^4.0.3
  glob: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.4

flutter:
